CREATE TABLE IF NOT EXISTS tasks (
    id VARCHAR(36) NOT NULL PRIMARY KEY, 
    name VARCHAR(50) NOT NULL, 
    summary VARCHAR(2500) NOT NULL,
    performed BOOLEAN NOT NULL DEFAULT false,
    createdAt DATETIME NOT NULL, 
    performedAt DATETIME NOT NULL
);
