version: '3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sword-health
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
  redis-server:
    image: bitnami/redis:latest
    container_name: redis-server
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
  redis-sentinel:
    container_name: redis-sentinel
    image: bitnami/redis-sentinel:latest
    environment:
      - REDIS_MASTER_HOST=127.0.0.1
    ports:
      - "26379:26379"
