apiVersion: apps/v1
kind: Deployment
metadata:
  name: sword-health
spec:
  selector:
    matchLabels:
      app.kubernetes.io/workload: api-sword-health
  template:
    metadata:
      labels:
        app.kubernetes.io/workload: api-sword-health
    spec:
      containers:
      - name: sword-health
        image: caiomartinspereira/sword-health:v0.0.1
        env:
        - name: DB_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: sword-health
              key: db-connection-string
        - name: ACCESS_SECRET
          valueFrom:
            secretKeyRef:
              name: sword-health
              key: access-secret
        - name: CACHE_URL
          value: localhost:6379
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3333
---
apiVersion: v1
kind: Service
metadata:
  labels:
      app.kubernetes.io/workload: api-sword-health
  name: sword-health
spec:
  selector:
    app.kubernetes.io/workload: api-sword-health
  ports:
  - port: 3333
    targetPort: 3333
